@startsalt
{+
{T
 + Sidebar | Main Content
 [Stepwize] | Bonjour, Kevin
 -- | --
 [ Mes guides ] | Dernière connexion : 01 October 2025
 [ Mes parcours ] | --
 [ Suivi utilisateurs ] | Mes guides
 [ Impact ] | [ Rechercher un guide... ] [ Nouveau guide ]
 | --
 | Liste des guides
 | [ Guide 1 ] [ Guide 2 ] [ Guide 3 ]
}
}
@endsalt
